ALTER TABLE "PayrollStructure" ADD COLUMN "monthlyWage" DECIMAL NOT NULL DEFAULT 50000;
ALTER TABLE "PayrollStructure" ADD COLUMN "workingDaysPerWeek" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "PayrollStructure" ADD COLUMN "breakTimeHours" DECIMAL NOT NULL DEFAULT 1;
ALTER TABLE "PayrollStructure" ADD COLUMN "pfRate" DECIMAL NOT NULL DEFAULT 12;
ALTER TABLE "PayrollStructure" ADD COLUMN "professionalTax" DECIMAL NOT NULL DEFAULT 200;
